- README.md
- cmd/Main.hs
- graphql-api.cabal
- package.yaml
- src/GraphQL.hs
- src/GraphQL/Muckaround.hs
- src/GraphQL/Schema.hs
- stack.yaml
I want to use graphql-haskell, so renamed the repo and moved the package from Data.GraphQL to GraphQL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jml/graphql-api/1)
> Rename & rejuggle

- stack.yaml
Might as well stay on the edge while we're in early development
> Use latest lts from Stackage

- graphql-api.cabal
- package.yaml
- tests/Doctests.hs
Doesn't actually add any doctests--that'll come later.
Review & merge #16 before reviewing this. Conflicts with #14.
Fixes #13.
> Add support for doctests

- docs/source/tutorial/Introduction.lhs
- src/GraphQL/Server.hs
- tests/Examples/UnionExample.hs
- tests/TypeApiTests.hs
This is an attempt to remove the `:<> ()` part in our handlers.
> No more ()

- docs/source/tutorial/package.yaml
- docs/source/tutorial/tutorial.cabal
- stack.yaml
We want the tutorial to at least build on CI.
> Add building of tutorial to stack.yaml. Closes #33.

- README.md
> Add readthedocs badge to README

- graphql-api.cabal
- package.yaml
- tests/ASTTests.hs
- tests/TypeTests.hs
Makes warnings fail the build. 
Not sure I'm a huge fan of the Enum API, but that's an issue for another day.
> Fix warnings

- src/GraphQL/Server.hs
We require it everywhere else. I somewhat arbitrarily decided to use a qualified import, except for typeclasses and symbols.
> Explicit import for GraphQL.API

- docs/source/tutorial/Introduction.lhs
- graphql-api.cabal
- src/GraphQL/API.hs
- src/GraphQL/Resolver.hs
- tests/Examples/FileSystem.hs
- tests/TypeApiTests.hs
> Some cosmetic fixes

- src/GraphQL/Internal/Validation.hs
- tests/ValidationTests.hs
Somehow these changes from #46 got lost.
> Validation

- circle.yml
- graphql-api.cabal
- src/GraphQL/API.hs
- src/GraphQL/API/Enum.hs
- src/GraphQL/Internal/Output.hs
- src/GraphQL/Internal/Schema.hs
- src/GraphQL/Resolver.hs
- src/GraphQL/Value.hs
- src/GraphQL/Value/FromValue.hs
- src/GraphQL/Value/ToValue.hs
- stack.yaml
- tests/Examples/InputObject.hs
- tests/ValueTests.hs
wait until your merge before reviewing
> Generic from value

- src/GraphQL/Resolver.hs
- tests/Examples/FileSystem.hs
- tests/Examples/UnionExample.hs
I've been going back and forth on this one for a while. There are good arguments for and against, but I'm 60:40 now on making the list handler itself monadic so here's the branch.
> Make list handlers themselves monadic on top of the elements.

- graphql-api.cabal
- src/GraphQL/Resolver.hs
- src/GraphQL/Value/ToValue.hs
- tests/EndToEndTests.hs
- tests/ExampleSchema.hs
- tests/ResolverTests.hs
- tests/SchemaTests.hs
- tests/Spec.hs
As discussed, end-to-end tests. By no means a full battery, but it should be enough to give the general idea.
I rebased the previous PR and incorporated @teh's fixes from #78. 
The "nested queries" test asserts a bad result. Asserting the correct result would fail. I figure this is the best way to document the behaviour. I'm pretty sure it's a release blocker, but I'd like to get this PR in more-or-less as is, without any further scope expansion.
> End-to-end tests

- src/GraphQL/Internal/AST.hs
- src/GraphQL/Internal/Encoder.hs
- src/GraphQL/Value.hs
- tests/EndToEndTests.hs
- tests/ExampleSchema.hs
> Rename `getNameText` to `unName`

- graphql-api.cabal
- src/GraphQL.hs
- src/GraphQL/API.hs
- src/GraphQL/API/Enum.hs
- src/GraphQL/Internal/AST.hs
- src/GraphQL/Internal/Encoder.hs
- src/GraphQL/Internal/Name.hs
- src/GraphQL/Internal/Output.hs
- src/GraphQL/Internal/Schema.hs
- src/GraphQL/Internal/Syntax/AST.hs
- src/GraphQL/Internal/Syntax/Encoder.hs
- src/GraphQL/Internal/Syntax/Parser.hs
- src/GraphQL/Internal/Syntax/Tokens.hs
- src/GraphQL/Internal/Validation.hs
- src/GraphQL/Resolver.hs
- src/GraphQL/Value.hs
- src/GraphQL/Value/FromValue.hs
- tests/ASTTests.hs
- tests/EndToEndTests.hs
- tests/ExampleSchema.hs
- tests/ResolverTests.hs
- tests/SchemaTests.hs
- tests/ValidationTests.hs
- tests/ValueTests.hs
Fixes #70. See https://facebook.github.io/graphql/#sec-Inline-Fragments.
Doing this now because I want to work on #59, and it'll be easier for me if I'm working from a known correct base. 
This PR depends on #83 (and thus #82). Probably review & merge those first before this one.
> Make type condition optional for inline fragments

- src/GraphQL/API/Enum.hs
- src/GraphQL/Internal/Validation.hs
- src/GraphQL/Resolver.hs
- src/GraphQL/Value.hs
- tests/EndToEndTests.hs
- tests/ExampleSchema.hs
Super easy to add these, although I discovered & fixed some bugs while at it.
Also identified some weak spots in the API. Rather than fixing these, which would take brain power I simply don't have right now, I've annotated them with TODOs.
> More tests

- README.md
rendered: https://github.com/jml/graphql-api/blob/7a6caa5415ecadba50eeda061d79d4a96c47489c/README.md
feel free to update / push to this branch
> Draft readme.

- src/GraphQL/Internal/Validation.hs
- src/GraphQL/Resolver.hs
- src/GraphQL/Value.hs
- src/GraphQL/Value/ToValue.hs
- tests/EndToEndTests.hs
> Revise TODOs

- circle.yml
- graphql-api.cabal
- package.yaml
Creating PR to verify CircleCI config.
> Don't build -Werror by default

- src/GraphQL/Resolver.hs
- tests/EnumTests.hs
- tests/ResolverTests.hs
Made the change to monadic. ~It seems self-contained to me, so I'm
wondering why~ this would be a breaking change as mentioned in issue #118.
> Close #118. Make resolver for Enum monadic. 

- CHANGELOG.rst
- graphql-api.cabal
- package.yaml
- src/GraphQL/Internal/Schema.hs
- src/GraphQL/Internal/Syntax/AST.hs
- src/GraphQL/Internal/Validation.hs
- src/GraphQL/Resolver.hs
- stack.yaml
> hide protolude redifined imports

- CHANGELOG.rst
- src/GraphQL/API.hs
- src/GraphQL/Resolver.hs
- tests/ExampleSchema.hs
- tests/Examples/InputObject.hs
Also removes unused DefaultArgument.
Fixes #149. Fixes #148.
> Move Defaultable into GraphQL.API

- src/GraphQL/Internal/Value/FromValue.hs
- tests/ValueTests.hs
This PR just adds a test to https://github.com/haskell-graphql/graphql-api/pull/178
> Add tests for generic fixes

- README.md
With the merged pull request #224, version 0.4.0 allows handlers to return errors. This change requires the use of a different function in the handler. This file change updates the README.md file to reflect this updated version.
> Update README.md with changes from #224
