haskell-graphql/graphql-api

README.md, tests/TypeApiTests.hs
0f1b8d8 introduced a compilation failure in the tests. This fixes that.
=> Fix failing build

circle.yml
Fixes #12
If you go to the [Artifacts tab of the build page](https://circleci.com/gh/jml/graphql-api/29#artifacts/containers/0) you can see a link to the [generated haddock documentation](https://29-70682597-gh.circle-artifacts.com/0/tmp/circle-artifacts.zgAfleG/graphql-api/index.html). 
It's worth having a poke around, because it's almost immediately obvious that:
- we need more docs :smiley_cat: 
- our module structure isn't super obvious to newcomers (or even to me!)
=> Build Haddock documentation in CI

src/GraphQL/Definitions.hs, src/GraphQL/TypeApi.hs, tests/Examples/UnionExample.hs, tests/TypeApiTests.hs, tests/TypeTests.hs
Also,
* remove some redundant parens
* copious doc comments for `(:<>)` and `(:>)`
* move `(:<>)` to typeapi
=> Explicit export list for definitions

HLint.hs, graphql-api.cabal, src/GraphQL/Output.hs, src/GraphQL/Schema.hs, src/GraphQL/TypeApi.hs, src/GraphQL/Value.hs, tests/Spec.hs, tests/ValidationTests.hs, tests/ValueTests.hs
I started out moving `Name` to the `Value` module with the intent of not adding any new TODOs. I ended up adding three, with a much bigger PR than I expected.
That's because I tried to eliminate the TODO that asked `What the heck does unionObject do?` I wrote a test to figure it out and found that it constructed invalid objects--objects with duplicate field names. I really don't want to ever have that bug again, so I jotted down a property and updated the types to give `Object` smart constructors so it's now only possible to construct Objects with unique field names.
To be honest, I still don't understand why `unionObjects` is the right behaviour in the union resolver, but I'm certain that its old behaviour was definitely wrong.
* Start of tests for `GraphQL.Value`
* Remove duplication of …
=> Move Name to Value module and make invalid Objects impossible

src/GraphQL/Definitions.hs, src/GraphQL/Output.hs, src/GraphQL/Schema.hs, src/GraphQL/TypeApi.hs, src/GraphQL/Value.hs, tests/TypeTests.hs, tests/ValueTests.hs
The quest to remove TODOs never ends. Although this removes one, it makes another.
Builds on https://github.com/jml/graphql-api/pull/24, so review & merge that before reviewing this (or just review https://github.com/jml/graphql-api/pull/26/commits/ddbd8afbb4723f15236a039618a09a925cec0946).
Was going to do QuickCheck instances in this as per #23 but this turned out to be more complicated than expected and also now I really have to go.
Name is restricted in value, so when we have something that accepts a `Name` as a parameter, it should be able to trust that it's valid.
Stopped exporting `Name` constructor and now export two constructors:
1. `makeName`
2. `unsafeMakeName`
They do what they say on the tin.
There are three use-cases for `unsafeMakeName`:
1. In tests, where we are passing a …
=> Smart constructor for Name

graphql-api.cabal, package.yaml, src/GraphQL/Value.hs, tests/ValueTests.hs
Pretty boring (at last). Depends on #26.
Fixes #23.
Note that `List` is too generously typed. I can't think of a good way of encoding homogeneous lists without adding a type parameter. I think we'll have to suck that one up.
=> QuickCheck for Values

graphql-api.cabal, package.yaml, src/GraphQL/API.hs, src/GraphQL/Server.hs, src/GraphQL/Value.hs, tests/Doctests.hs, tests/Examples/UnionExample.hs, tests/TypeApiTests.hs, tests/TypeTests.hs, tests/ValueTests.hs
I figure we're using it so much that it basically counts as a style thing that should be consistently available across the code base.
=> Make TypeApplications a default language extension

scripts/lint, src/GraphQL/Internal/AST.hs, src/GraphQL/Internal/Encoder.hs, src/GraphQL/Internal/Parser.hs, src/GraphQL/Value.hs, tests/ASTTests.hs
Turns out graphql doesn't support escaped strings. This makes it do so by re-using Aeson's code, on the assumption that GraphQL strings are identical to JSON strings.
=> Roundtrip strings

graphql-api.cabal, package.yaml, src/GraphQL/Internal/Parser.hs, src/GraphQL/Value.hs, tests/ASTTests.hs
#37 does this for strings, this does it for all values. Review & merge #37 first to see a good diff for this.
Adds quickcheck tests for roundtripping values. They currently fail, but not on every run. I've added a test that exercises the broken path, but I haven't had time to minimize.
It might be useful to begin by adding better shrinking support to the `Arbitrary` instances we already have. That's what I'm going to do next time I face quickcheck failures.
=> WIP: Full value roundtrip

src/GraphQL/Server.hs, tests/TypeApiTests.hs
I got this down to a fairly minimal change. I don't have time right now to figure out why this changes both error messages, but I suspect something to do with MonadThrow.
=> Change error handling behaviour

.gitignore, src/GraphQL/API.hs, src/GraphQL/Internal/AST.hs, src/GraphQL/Internal/Encoder.hs, src/GraphQL/Internal/Output.hs, src/GraphQL/Internal/Parser.hs, src/GraphQL/Internal/Schema.hs, src/GraphQL/Internal/Validation.hs, src/GraphQL/Server.hs, src/GraphQL/Value.hs, tests/ASTTests.hs, tests/TypeTests.hs, tests/ValidationTests.hs, tests/ValueTests.hs
* Move all the name stuff from `Value` to `AST`
* Guarantee that only valid names ever appear in the `AST` or anywhere else
* Add a `HasName` type class that is implemented by all named things in the schema (can be extended to other things later, this is just the only place I needed it)
* Change the `getFooDefinition` methods to return `Either NameError Foo`. This involves changing most of the code to be applicative, which in turn involves a fair chunk of using the composition operator. Sorry.
* While doing that, removed some duplication (mostly because it was less boring than typing the same thing twice)
* Update Server module to use the API module and to get names from there, rather than directly from symbols. This simplifies some of the types (but I tried to tread lightly here). Dodgy …
=> Guaranteed correct name in AST

graphql-api.cabal, src/GraphQL/Internal/AST.hs, src/GraphQL/Internal/Arbitrary.hs, src/GraphQL/Server.hs, src/GraphQL/Value.hs, tests/ValueTests.hs
We talked about this earlier, so hopefully this will be uncontroversial:
* Split `ReadValue` typeclass into one that converts values into Haskell objects (`FromValue`) and one that provides defaults (`Defaultable`)
* Change `FromValue` to operate on our "literal" values (which won't have variables, and won't have duplicate fields), rather than AST values (which can be anything that's syntactically valid)
* Change the interface for `Defaultable` to be `Maybe` rather than `Either`, since I figure the error message will always be the same, and users won't want to customise it.
* Roundtripping methods & tests 
If there are conflicts with your error branch, I'll resolve them here.
=> Extract FromValue from ReadValue

src/GraphQL/Internal/AST.hs, src/GraphQL/Internal/Encoder.hs, src/GraphQL/Internal/Parser.hs, src/GraphQL/Internal/Validation.hs, tests/ASTTests.hs, tests/Examples/UnionExample.hs, tests/TypeApiTests.hs, tests/ValidationTests.hs
In #42, @teh was surprised about the behaviour of node names. This is partly due to the structure of the AST, which previous just said that an anonymous query was a query with an empty name. 
This PR gives anonymous queries a distinct branch in the AST, updates the validation logic to be a bit more explicit, and fixes the parser while it's at it (it more or less falls out from having correct types). 
Also changes the top level "document" concept, splitting it into query document and schema document. The reasoning here is that you just can't send type definitions in a query, so don't bother trying to parse them while parsing queries. The upshot is that it further simplifies validation.
=> Anonymous queries

graphql-api.cabal, package.yaml, src/GraphQL/Server.hs, tests/Examples/FileSystem.hs, tests/Examples/UnionExample.hs, tests/Spec.hs, tests/TypeApiTests.hs
The main change here is that instead of an `Either` we now have a `Result` which accumulates errors and values at the same time.
* This is still a draft but wanted to get your opinion early 
* I'm not super happy with `ResolveFieldResult` but not sure ATM how to phrase better (other than maybe a separate `data` type)
* MonadIO & throw are gone
* Error accumulation needs a nicer representation but a I can't tell from the [description](https://facebook.github.io/graphql/#sec-Errors) what errors for specific fields should look like.
=> Move error handling closer to the spec

src/GraphQL/Internal/AST.hs, src/GraphQL/Internal/Encoder.hs, src/GraphQL/Internal/Parser.hs, src/GraphQL/Value.hs, tests/ASTTests.hs, tests/ValueTests.hs
Turns out the AST wouldn't parse 'null'. Who knew?
Also had to make some changes to generators to make them run fast.
=> Parse null

src/GraphQL/Internal/Validation.hs, tests/ValidationTests.hs
The `Validation` module now contains a structured `QueryDocument` data type ready for use by the executor.
Scope of the module is defined by the [Validation](https://facebook.github.io/graphql/#sec-Validation) chapter of the spec, except as otherwise noted.
Over-arching philosophy is to do "constructive" validation, making new objects that are the ones we wish we had, and reporting errors where not found. Thus, we use Maps to show that names are unique.
There is still more to do, but this is big enough and complete enough that it should be reviewed & merged.
It will probably be easier to review the new file than to review the diff.
=> Implement most of query validation

src/GraphQL/Server.hs, tests/TypeApiTests.hs
This isn't the structure we'll want to keep forever, but it's a good starting point, and having the richer types means the compiler will help us when we introduce validation.
I reckon this fixes #20
=> Structured errors

graphql-api.cabal, src/GraphQL/API.hs, src/GraphQL/API/Enum.hs, src/GraphQL/Internal/AST.hs, src/GraphQL/Resolver.hs, tests/TypeTests.hs
Rough implementation, has some nice properties though not encoded as well as they could be:
* calling `enumValues` fails if there is an invalid name (right now through an incomplete pattern match). `enumValues` is mostly internal so we can decide how we want to fail here. Should tie in with general validation.
* Checks for unary constructors and doesn't compile if it's not. (Try `instance GraphQLEnum A`)
=> Generic enum

graphql-api.cabal, package.yaml, src/GraphQL.hs, src/GraphQL/Internal/AST.hs, src/GraphQL/Internal/Execution.hs, src/GraphQL/Internal/OrderedMap.hs, src/GraphQL/Internal/Output.hs, src/GraphQL/Internal/Validation.hs, src/GraphQL/Resolver.hs, src/GraphQL/Value.hs, tests/Examples/FileSystem.hs, tests/Examples/UnionExample.hs, tests/OrderedMapTests.hs, tests/Spec.hs, tests/TypeApiTests.hs, tests/TypeTests.hs, tests/ValueTests.hs
This is a pretty big change. I'm sorry that it will make the review harder, but I struggled to separate it into meaningful chunks in my head.
GitHub hides `Value` and `Validation` for me, and I think that might be the best way to review it. Review the stuff that _uses_ those first, then review those two to see how it's all implemented.
The goal was to substitute variables. This meant restructuring `Value` (as discussed), and parametrising most of the types in the `Validation` module by value, to indicate whether they are AST values, valid values that might be variables that don't have definitions, valid values that might be variables that _do_ have definitions, or just concrete values.
One nice thing that falls out of the approach Validation was already taking is that we get the dynamic …
=> Validation for values and variables, plus substitution

src/GraphQL.hs, src/GraphQL/API/Enum.hs, src/GraphQL/Internal/AST.hs, src/GraphQL/Internal/Execution.hs, src/GraphQL/Internal/Output.hs, src/GraphQL/Internal/Validation.hs, src/GraphQL/Resolver.hs
As mentioned in #66. 
Lots of human-readable errors.
I haven't actually verified any of them, but I reckon this is an improvement, and should signal clearly to our users that we care about this sort of thing.
Changed the union handling a bit because I couldn't understand the error conditions well enough. See commit message on c0e0f67 for rationale.
=> Format error typeclass

graphql-api.cabal, src/GraphQL.hs, src/GraphQL/API.hs, src/GraphQL/API/Enum.hs, src/GraphQL/Internal/AST.hs, src/GraphQL/Internal/Encoder.hs, src/GraphQL/Internal/Name.hs, src/GraphQL/Internal/Output.hs, src/GraphQL/Internal/Schema.hs, src/GraphQL/Internal/Syntax/AST.hs, src/GraphQL/Internal/Syntax/Encoder.hs, src/GraphQL/Internal/Syntax/Parser.hs, src/GraphQL/Internal/Syntax/Tokens.hs, src/GraphQL/Internal/Validation.hs, src/GraphQL/Resolver.hs, src/GraphQL/Value.hs, src/GraphQL/Value/FromValue.hs, tests/ASTTests.hs, tests/EndToEndTests.hs, tests/ExampleSchema.hs, tests/ResolverTests.hs, tests/SchemaTests.hs, tests/ValidationTests.hs, tests/ValueTests.hs
Includes changes in #82, so maybe review & merge that first.
I've been meaning to do this for some time. The syntax modules are all pretty self-contained, and putting them in a subdirectory means that `ls -1 src/GraphQL/Internal` shows a more meaningful list of what we're doing.
The big exception is `Name`-related stuff, which gets used everywhere. Because it's such an important concept, I've extracted it to its own internal module, `GraphQL.Internal.Name`.
=> Move syntax modules to Syntax sub-package

src/GraphQL/Resolver.hs, tests/EndToEndTests.hs, tests/ResolverTests.hs
Before this change we tried to read field arguments even if the query
never requested the actual field itself. This is obviously wrong
because we'd never supply arguments for fields we're not requesting.
Even if all fields were optionsal we'd still waste CPU cycles.
=> Resolve field name before checking field arguments. Closes #81.

stack.yaml
Also drop graphql as a dependency.
=> Bump to stackage nightly to get ghc 8.0.2

HLint.hs, graphql-wai/src/GraphQL/Wai.hs, src/GraphQL.hs, src/GraphQL/Internal/OrderedMap.hs, src/GraphQL/Internal/Schema.hs, src/GraphQL/Internal/Syntax/AST.hs, src/GraphQL/Internal/Validation.hs, src/GraphQL/Resolver.hs, src/GraphQL/Value.hs, tests/EndToEndTests.hs, tests/Examples/UnionExample.hs, tests/ValidationTests.hs
Fixes #59 
This makes the job of the resolver much simpler. It doesn't have to worry about inline fragments or whatever, it only deals with ordered maps of fields. 
Unfortunately, it also makes the job of the validator more complex. Recursing through the whole query to merge fields is a bit involved. Defining some generic operations on `OrderedMap` made this much easier to think about.
This PR also introduces the notion of types into the validator. We need to know the type of the object we're building a selection set for, and we need to know the definitions of the type conditions. This (to me) means building and providing a value that represents the whole schema, and making sure each resolver has it. This in turn means passing a new value, `allTypes` down through each resolver. I think …
=> Merge selections in a set into ordered map of fields

CHANGELOG.rst, src/GraphQL/Internal/Name.hs, src/GraphQL/Internal/Output.hs, src/GraphQL/Internal/Schema.hs, src/GraphQL/Internal/Syntax/AST.hs, tests/ASTTests.hs, tests/ResolverTests.hs, tests/SchemaTests.hs, tests/ValidationTests.hs, tests/ValueTests.hs
Means that we can just say `"dog"` when we want a `Name`, and then the code will panic if we specify an invalid name (e.g. `"9dog"`).
=> Make Name an overloaded string

graphql-api.cabal, package.yaml, src/GraphQL/API.hs, src/GraphQL/API/Enum.hs, src/GraphQL/Internal/Execution.hs, src/GraphQL/Internal/Schema.hs, src/GraphQL/Internal/Syntax/AST.hs, src/GraphQL/Internal/Syntax/Encoder.hs, src/GraphQL/Internal/Syntax/Parser.hs, src/GraphQL/Internal/Validation.hs, src/GraphQL/Resolver.hs, src/GraphQL/Value/FromValue.hs, stack.yaml
Hi,
this should update graphql-api to compile with protolude 0.2 on both GHC 8.0.2 and 8.2.1.
=> Update to protolude 0.2

CHANGELOG.rst, src/GraphQL/Resolver.hs, tests/EndToEndTests.hs, tests/ResolverTests.hs
I'm not happy with this solution because of the extra monad level
introduced.
pure (Just (pure value))
is not a good way to return a Maybe. Not sure how to fix better ATM.
=> Correctly propagate Maybe handlers. Closes #102 and #119.

README.md
Purpose: Decrease the time needed for users to orientate.
=> Add tutorial link for readthedocs.io to README.md

graphql-api.cabal, package.yaml
Also took the liberty to change the synopsis field. It lacked specificity.
Edited `package.yaml` then called `hpack`. Apologies for the meaningless churn in `graphql-api.cabal`.
=> Update cabal information on hackage. Closes #107.

src/GraphQL/Internal/Name.hs, src/GraphQL/Internal/Syntax/AST.hs, src/GraphQL/Internal/Syntax/Encoder.hs, src/GraphQL/Internal/Syntax/Parser.hs
Following todo formerly in src/GraphQL/Internal/Syntax/AST.hs:
TODO: Just make Node implement HasName.
Declared Node as instance of HasName and wrote implementation of
getname for it.
Because of a cyclic dependency between Name and AST, moved the Name
specific code from GraphQL.Internal.Syntax.AST module into the
GraphQL.Internal.Name module.
Updated imports and exposures in the AST and Name modules described
above.
Simple import and qualified name changes to:
GraphQL/Internal/Syntax/Encoder
GraphQL/Internal/Syntax/Parser
=> Make Node instance of HasName. Implement getName.

docs/source/tutorial/tutorial.cabal, graphql-wai/graphql-wai.cabal, src/GraphQL/Internal/Execution.hs, src/GraphQL/Internal/Name.hs, src/GraphQL/Internal/Syntax/AST.hs, src/GraphQL/Internal/Syntax/Encoder.hs, src/GraphQL/Internal/Syntax/Parser.hs, src/GraphQL/Internal/Validation.hs, tests/ASTTests.hs, tests/ValidationTests.hs
```
"{\"query\":\"query {\\n  greeting(who: \\\"Tim\\\")\\n}\"}"
```
Notice that the query (immediately after the start of the JSON field `query:`) has no operationName, i.e. it's anonymous.
```
Just (GraphQLPostRequest {query = "query {\n  greeting(who: \"Tim\")\n}", operationName = "", variables = fromList []})
```
by a custom/temporary Aeson parser.
:blush: I didn't record it, and now it's gone. Something along the lines of:
```
Just(Error{"query document error!definition error!query"})
```
Not exactly, but that was the gist of it.
Realized that the parser might be choking on the absence of the `operationName`, so tried to apply `optempty` to `nameParser` but Name was not an instance of Monoid. Changed that and ¡viola! it worked (sounds easy, but I learned something about applying …
=> Fix error on anonymous query

docs/source/tutorial/tutorial.cabal, graphql-wai/graphql-wai.cabal, src/GraphQL/Internal/Execution.hs, src/GraphQL/Internal/Name.hs, src/GraphQL/Internal/Syntax/AST.hs, src/GraphQL/Internal/Syntax/Encoder.hs, src/GraphQL/Internal/Syntax/Parser.hs, src/GraphQL/Internal/Validation.hs, tests/ASTTests.hs, tests/ValidationTests.hs
Add tests in ASTTests.hs:
- parses anonymous query documents
- changed previous test of same name to: parses shorthand syntax documents
- parses anonymous query with variables
Added tests in ValidationTests.hs:
- Treats anonymous queries as valid
- Treats anonymous queries with variables as valid
=> Add tests for anonymous queries w|w/o variables

.circleci/config.yml, src/GraphQL/API.hs, src/GraphQL/API/Enum.hs, src/GraphQL/Internal/Execution.hs, src/GraphQL/Internal/Schema.hs, src/GraphQL/Internal/Syntax/AST.hs, src/GraphQL/Internal/Syntax/Encoder.hs, src/GraphQL/Internal/Syntax/Parser.hs, src/GraphQL/Internal/Validation.hs, src/GraphQL/Value/FromValue.hs, tests/SchemaTests.hs, tests/ValidationTests.hs
Triggered by a discussion on #154. Commit history pretty much outlines what's changed.
=> Make warnings fail the build

src/GraphQL/API.hs
Fixes #95 
I kept `DefinesTypes` because it's not the same as all the API type classes. I still have no idea what on earth `BuildFieldResolver` does. Pretty sketchy on `RunUnion` and `RunFields` too.
=> Consistent name for union type definitions

CHANGELOG.rst, graphql-api.cabal, package.yaml
- Version bump
- Changelog update
- Description improvement
Will tag master revision after merging and release to Hackage.
=> Prepare to release 0.3.0

CHANGELOG.rst, src/GraphQL.hs, src/GraphQL/API.hs, src/GraphQL/Internal/API.hs, src/GraphQL/Internal/Resolver.hs, src/GraphQL/Internal/Schema.hs, tests/SchemaTests.hs
We added a `NonEmptyList` type *really* early in our explorations. Haskell already has one, so we should use that.
This has a knock-on: the type system now prevents us from constructing schemas with empty field lists, etc. This means we need to change error types a little.
I would have liked to write tests for this, but, you know how it is.
=> Drop custom NonEmptyList type

examples, examples/InputObject.hs, examples/UnionExample.hs, graphql-api.cabal, package.yaml, tests/EndToEndTests.hs, tests/ExampleSchema.hs, tests/Spec.hs, tests/doctests/Main.hs
We had a weird thing where top-level `examples` dir symlinked into tests, we used the test suite to compile the examples, and then used the doctests to check the examples worked.
At least one side effect of this is we get cabal warnings all the time:
```
Warning: There were multiple candidates for the Cabal entry " Examples.InputObject
* /Users/jml/src/graphql-api/Examples/InputObject.hs
picking: /Users/jml/src/graphql-api/tests/Examples/InputObject.hs
Warning: There were multiple candidates for the Cabal entry " Examples.UnionExample
* /Users/jml/src/graphql-api/Examples/UnionExample.hs
picking: /Users/jml/src/graphql-api/tests/Examples/UnionExample.hs
```
I've made the examples executables, which means they can be edited & run, which I think is a nice property. This lets us remove the …
=> Make examples programs

.circleci/config.yml, scripts/hpc-ratchet
Adds a Python script to compare coverage data before and after.
Why not use hpc-coveralls? Because it doesn't work with Stack (https://github.com/guillaume-nargeot/hpc-coveralls/issues/47), and it doesn't work with multiple packages (https://github.com/guillaume-nargeot/hpc-coveralls/issues/51). Since the main thing I want is a ratchet, it's easiest just to write a script.
[Generated coverage report](https://399-70682597-gh.circle-artifacts.com/0/root/project/.stack-work/install/x86_64-linux/lts-10.4/8.2.2/hpc/combined/all/hpc_index.html)
=> Ratchet test coverage

graphql-api.cabal, scripts/hpc-ratchet, src/GraphQL/Internal/Execution.hs, src/GraphQL/Internal/Schema.hs, src/GraphQL/Internal/Syntax/AST.hs, src/GraphQL/Internal/Validation.hs, tests/ASTTests.hs, tests/EndToEndTests.hs, tests/SchemaTests.hs, tests/ValidationTests.hs
This PR is a required step towards the resolution of #145. It improves the validation of type declaration in variable definitions. For instance it validates the fact that when a document contains $myVariable: MyVar, then the MyVar type actually exists in the schema and it's an InputType.
Remaining tasks:
PS: this is my first "real" attempt to write haskell so please, any insight would be greatly appreciated.
**Edit: I added DefinesTypes instances on arguments because failing tests were simply not finding their argument types in the schema (schema in the sense of what is returned by makeSchema)**
=> Variable definitions validation

src/GraphQL/Internal/Value/FromValue.hs
The old FromValue code makes the assumption that product types are always of the shape `(a :*: (b :*: c))`.
However GHC  balances product and sum types (https://hackage.haskell.org/package/base-4.11.0.0/docs/GHC-Generics.html#g:9)
Resolves #173
=> Properly recurse into :*:

scripts/hpc-ratchet, src/GraphQL/Internal/API.hs
We simplify `GenericInputObjectFieldDefinitions` by using
tree-recursion, resulting in better error messages. Example
code to reproduce below, where the 'true' error is usage of
lists.
```hs
data family Test :: Nat -> Type
data instance Test 1 = Test
{ testField1 :: Int32
, testField2 :: Text
, testField3 :: Text
, testField4 :: [Int32]
} deriving (Show, Generic)
instance HasAnnotatedInputType Test
```
Before
```
• No instance for (GraphQL.Internal.API.GenericInputObjectFieldDefinitions
((S1
('MetaSel
('Just "testField1")
'NoSourceUnpackedness
'NoSourceStrictness
'DecidedLazy)
(Rec0 Int32)
:*: S1
('MetaSel
('Just "testField2")
'NoSourceUnpackedness
'NoSourceStrictness
'DecidedLazy)
(Rec0 Text))
:*: (S1
('MetaSel
('Just "testField3")
'NoSourceUnpackedness
'NoSourceStrictness
'DecidedLazy) …
```
=> Simplify GenericInputObjectFieldDefinitions

graphql-wai/src/GraphQL/Wai.hs, scripts/hpc-ratchet, src/GraphQL.hs, src/GraphQL/Internal/Resolver.hs, src/GraphQL/Resolver.hs
This is one of a series of PR's I am doing as small improvements that are suggesting on the code itself.
This constraints the resolving of the operation (or the root of the query) to only objects. Removing the unnecessary check that was done checking if the result of the resolving was indeed an object or not.
I want to implement schema introspection and for that I have been reading the code to understand where and how to add it. To be able to handle the `__schema` field, it's necessary a resolver that we are sure that is the entrypoint so we can build up the schema downwards from it. This change makes it possible.
=> Improve type safety on operation interpreting
